### ISSUE TITLE
Dependency on krbclient

### ISSUE THREAD

**Issue by KimVNguyen** [jacobludriks/winrmjs#1]
It deems like Kerberos support is slated somewhere down the line.  However the current package.json requires krbclient.  When running an NPM install the following output will display:

..\src\krbclient.cc(5): fatal error C1083: Cannot open include file: 'gssapi/gs
sapi.h': No such file or directory [C:\Users\knguyen\AppData\Roaming\npm\node_m
odules\winrmjs\node_modules\krbclient\build\krbclient.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` fai
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (c:\Program Files\nodejs\node_modules
npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810
12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "c:\\Program Files\\nodejs\\node_modules\\npm\\node_mod
les\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\knguyen\AppData\Roaming\npm\node_modules\winrmjs\node_mod
les\krbclient
gyp ERR! node -v v0.10.31
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok
npm ERR! krbclient@0.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the krbclient@0.1.0 install script.
npm ERR! This is most likely a problem with the krbclient package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls krbclient
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\node
s\\node_modules\\npm\\bin\\npm-cli.js" "install" "winrmjs" "-g"
npm ERR! cwd d:\git\Hurdr
npm ERR! node -v v0.10.31
npm ERR! npm -v 1.4.23
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     d:\git\Hurdr\npm-debug.log
npm ERR! not ok code 0

The Readme.md from your node-krbclient project shows that it is very much a work in progress.  Reccomend that you remove this dependency until the other repository is completed.

**Comment by jacobludriks** [comment]
unfortunately this project has become less of a priority at the moment, but this will be fixed in the next month. in the meanwhile, please manually remove from package.json
