### ISSUE TITLE
Not Found HTTP Error 404. The requested resource is not found.

### ISSUE THREAD

**Issue by abedzaben28** [jacobludriks/winrmjs#4]
i think the configurations on the remote server not enough to run through the code, i keep get:
Not Found
HTTP Error 404. The requested resource is not found.
need to configure the remote host to support, directly from cmd on my local laptop i can run any command of the remote easily by the following command:
winrs -r:http://remotemachinename:5985 -u:remoteusername "dir c:",
now i'm stuck with winrmjs still keep get Not found any extara configurations for this ?

**Comment by jacobludriks** [comment]
this code is no longer maintained. feel free to fork it and fix it :)
